Repository sosow0212/atwoz, pull requests merged in 2024-07, with the labels that each got.

#36 fix: API 문서 경로를 수정한다
  src/docs/asciidoc/index.adoc
Labels: 버그 수정

#40 feat: 레디스 적용 및 로그아웃 api 추가
  .github/workflows/backend-test-when-pr.yml
  build.gradle
  src/docs/asciidoc/admin.adoc
  src/main/java/com/atwoz/admin/application/auth/AdminAccessTokenProvider.java
  src/main/java/com/atwoz/admin/application/auth/AdminAuthService.java
  src/main/java/com/atwoz/admin/domain/admin/AdminRefreshToken.java
  src/main/java/com/atwoz/admin/domain/admin/AdminRefreshTokenRepository.java
  src/main/java/com/atwoz/admin/domain/admin/AdminTokenProvider.java
  src/main/java/com/atwoz/admin/domain/admin/service/AdminRefreshTokenProvider.java
  src/main/java/com/atwoz/admin/exception/AdminExceptionHandler.java
  src/main/java/com/atwoz/admin/exception/exceptions/InvalidRefreshTokenException.java
  src/main/java/com/atwoz/admin/infrastructure/auth/AdminJwtTokenProvider.java
  src/main/java/com/atwoz/admin/infrastructure/auth/AdminRedisRefreshTokenRepository.java
  src/main/java/com/atwoz/admin/ui/auth/AdminAuthController.java
  src/main/java/com/atwoz/admin/ui/auth/interceptor/AdminLoginValidCheckerInterceptor.java
  src/main/java/com/atwoz/admin/ui/auth/support/AdminTokenExtractor.java
  src/main/java/com/atwoz/admin/ui/auth/support/resolver/AdminRefreshTokenExtractionArgumentResolver.java
  src/main/java/com/atwoz/global/config/RedisConfig.java
  src/main/resources/application.yml
  src/test/java/com/atwoz/admin/application/auth/AdminAuthServiceTest.java
  src/test/java/com/atwoz/admin/fixture/AdminRefreshTokenFixture.java
  src/test/java/com/atwoz/admin/infrastructure/admin/AdminFakeRefreshTokenRepository.java
  src/test/java/com/atwoz/admin/infrastructure/auth/AdminRedisRefreshTokenRepositoryTest.java
  src/test/java/com/atwoz/admin/ui/auth/AdminAuthControllerTest.java
  src/test/java/com/atwoz/admin/ui/auth/interceptor/AdminLoginValidCheckerInterceptorTest.java
  src/test/java/com/atwoz/helper/MockBeanInjection.java
  src/test/resources/application.yml
Labels: 기능 추가

#43 refactor: yml에 레디스 설정 추가 및 레디스 repository 테스트 삭제
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/test/java/com/atwoz/admin/infrastructure/auth/AdminRedisRefreshTokenRepositoryTest.java
Labels: 리팩토링, 인프라
